# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do |lane, options|
  # Load secrets that are not commited to git
  Dotenv.load(".env.#{ENV['ENV']}.secret")
end

platform :android do
  desc "Deploy a new version to App Center"
  lane :hard_deploy do
    gradle(
      task: "clean assembleRelease",
      project_dir: "android",
    )

    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: "maelg-bam.tech",
      app_name: "Deployable-1",
      file: ENV["APK_PATH"],
    )

    gradle(
      task: "clean",
      project_dir: "android",
    )
  end
end
