name: Run tests

runs-on: macos-latest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint

  test:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
